config/routes.rb
Carsapp::Application.routes.draw do
  resources :posts

  get "contact_form/new"

  get "contact_form/create"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"
  resources :contact_forms
  resources :users
  resources :ads

  resources :cars
  
  resources :sessions

  resources :cars do

  resources :posts
	end

  get "pages/home"

  get "pages/about"

	match '/signin',  :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'
	match '/allcars', :to => 'cars#index2'
    match '/search',  :to =>'cars#search'
	

   root :to => 'pages#home'

end

app/models/car.rb
class Car < ActiveRecord::Base
	has_one :ad
	validate :reg, presence: true
	validates_uniqueness_of :reg
	has_many :posts, :dependent => :destroy
	
	def self.search(search)
	 search_condition =search + "%"
	 find(:all,:conditions =>['make LIKE ?',search_condition])
	 end
	 
	 geocoded_by :description
	after_validation :geocode, :if => :description_changed?
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :car


end

app/models/user.rb
class User < ActiveRecord::Base
	validates_uniqueness_of :email
	has_secure_password	
	validates_confirmation_of :password
	has_many :posts, :dependent => :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
protect_from_forgery
include ApplicationHelper


def authorise
	unless signed_in?
		store_location
		redirect_to signin_path, :notice => "Please sign in to access this page"
		
	
	end
end

 def authoriseAdmin
	unless signed_in? && @current_user.admin
		store_location
		redirect_to signin_path, :notice => "You need to be an administratot to preform this task"
	end
 end
	
  private
def store_location
	session[:return_to] = request.fullpath
end
    end
	

app/controllers/blogmailer.rb
def register(user) 
	if user
   	   @user = user 
           mail(:to => user.email, :subject => "Welcome Wheels site")
    end 
 end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
 before_filter except: [:show, :edit, :destroy]
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end
  
   def index2
    @cars = Car.all

    respond_to do |format|
      format.html # index2.html.erb
      format.json { render json: @cars }
    end
  end
   
  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def search
	@cars=Car.search params[:q]
	unless @cars.empty?
		render 'index'
	else
		flash[:notice]='no car matches that search'
		render 'index'
	end
  end	

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
  
  
  
end

app/controllers/contact.rb

def send_mail
  Emailer::deliver_contact_email(params[:email])
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @variable1=Time.current
  
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authorise
	def create
     @car = Car.find params[:car_id]
     @post = @car.posts.create params[:post]
     @post.user_id = @current_user.id
     @post.save							
			respond_to do |format|
				format.html { redirect_to @car }
			end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
			user = User.find_by_name(params[:name])	
		if user && user.authenticate(params[:password]) 			
			session[:user_id] = user.id	
			redirect_to allcars_path
		else  	 		
			flash.now[:error] = "Invalid name/password combination."      	
			render 'new'		    
		end
	end

  def destroy
	if signed_in?
			session[:user_id]=nil
  
	else
			flash[:notice] = "You need to sign in first"
	end
	redirect_to signin_path
	end 
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def euro(amount)
		number_to_currency(amount, :unit => '&euro;')
	end



 def signed_in?
       if session[:user_id].nil?
	return
       else
	@current_user = User.find_by_id(session[:user_id])
       end
  end
 end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
	<ul >
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
   <% end %>
    </ul>
    </div>

 <% end %>

<ul align="center">
  <div  class="field" align="center">
    <%= f.label :reg %><br />
    <%= f.text_field :reg %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :engine %><br />
    <%= f.select :engine, ["1.0", "1.2","1.3","1.4","1.5","1.6","1.8","2.0","2.2","2.6"], :include_blank => :true %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
     <%= f.select :size, ["saloon", "Hatchback","Humvee","truck"],:include_blank => :true %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :Location %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </ul>
<% end %>

app/views/cars/_search.html.erb

<%= form_tag("/search", :method => "get") do %>
<%= label_tag(:q,"Search For Car By Make:")%>
<%= text_field_tag(:q,params[:q],:id=>'q_field')%>
<%= submit_tag("Search")%>
<%end%>


app/views/cars/edit.html.erb
<h1 align="center">Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1 align="center" >Ads Available</h1>

<table align="center">
  <tr>
    <th>Reg</th>
    <th>Make</th>
    <th>Model</th>
    <th>Engine</th>
    <th>Size</th>
    <th>Price</th>
    <th>Photo</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.reg %></td>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= car.engine %></td>
    <td><%= car.size %></td>
    <td><%= euro(car.price) %></td>
    <td><%= car.photo %></td>
    <td><%= car.description %></td>
   <td><%= link_to 'Show', car %></td>
  </tr>
<% end %>
</table>

<br />

app/views/cars/index2.html.erb

<table>
  <tr>
    <th>Reg</th>
    <th>Make</th>
    <th>Model</th>
    <th>Engine</th>
    <th>Size</th>
    <th>Price</th>
    <th>Photo</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.reg %></td>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= car.engine %></td>
    <td><%= car.size %></td>
    <td><%= car.price %></td>
    <td><%= car.photo %></td>
    <td><%= car.description %></td>
    <td><%= link_to 'Show', car %></td>
  </tr>
<% end %>
</table>

app/views/cars/new.html.erb
<h1 align="center" >Place Advert</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div align="center">
<p>
  <b>Reg:</b>
  <%= @car.reg %>
</p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Engine:</b>
  <%= @car.engine %>
</p>

<p>
  <b>Size:</b>
  <%= @car.size %>
</p>

<p>
  <b>Price:</b>
  <%= @car.price %>
</p>

<p>
  <b>Photo:</b>
<%= image_tag(@car.photo ,:size=> "250x150") %>
</p>

<p>
  <b>Location:</b>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@car.latitude}%2C#{@car.longitude}" %>
</p>


<h2>Leave Offer below and phone number:</h2>
	<%= form_for([@car, Post.new]) do |f| %>
  		<%= f.text_area :content, :rows => 3 %> 
		<div class="actions">
			<%= f.submit "Post a Comment"%>
		</div>
	<% end %>
</p>
	
<% if @car.posts.empty? %>
  <% else %>
     <h2>Offers and comments</h2>
     <% @car.posts.reverse.each do |post| %>
     <p><%= post.content %>
        Posted <%= time_ago_in_words(post.created_at) %>
		
   <% end %>
<% end %>

<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

		<head>

<style> 
body {
    background-image: url("../assets/rails.jpg");
    background-color: #cccccc;
}
</style>
</head>
			  <title>Carsapp</title>
  
		</h1>
	</div>
	<div id="navigation">
		<ul>
		   <li><%= link_to 'Home',root_path %> </li>
	      <li><%= link_to 'Place ad', new_car_path %> </li>
		  <li><%= link_to 'view cars',cars_path %> </li>
		  <li><%= link_to 'Sign in',signin_path %> </li>
		  <li><%= link_to 'Sign up',new_user_path %> </li>
		   <li><%= link_to 'About', pages_about_path%> </li>
		   <li><%= mail_to 'zaidk2008@hotmail.com',"Contact us" %> </li>
		</ul>
	</div>
	<div id="banner">
	   
		<a href="https://www.facebook.com/Ferrari">
		<img src="../assets/fb.jpg" height=60 width=70 />
		
		<a href="http://instagram.com/luxuryvehicle">
		<img src="../assets/insta.jpg" height=60 width=70 />
		
		<a href="https://twitter.com/ferrariworldad">
		<img src="../assets/twit.jpg" height=60 width=70 />
		</a>
		  Created by Zaid Kurchied
	</div>

<ul>
	<% if !signed_in? %>
		<li><%= link_to "Sign In", signin_path %></li>		
	<% else %>
		<li>Signed in as <%= @current_user.name %></li>
		<li><%= link_to "Sign Out", signout_path %></li>

	<%end %>
		<div id="search" align="right" >
	<%=render :partial => 'cars/search' %>
       </div>
		
	
<%= yield %>
</head>

app/views/pages/about.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script> 
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideToggle("slow");
    });
});
</script>
 
<style> 
#panel, #flip {
    padding: 5px;
    text-align: center;
    background-color: #989898;
    border: solid 1px #c3c3c3;
}

#panel {
    padding: 50px;
    display: none;
}
</style>
</head>
<body>
 
<div id="flip">Click to Find more about us</div>
<div id="panel">
<ul style="list-style-type:disc">
	Here are some  useful link about this website 
  <li><a href="https://www.linkedin.com/pub/zaid-kurchied/66/49b/244?domainCountryName=&csrfToken=guest_token">Created by</a></li>
  <li><a href="http://www.dit.ie">Company</li>
  <li><a href="http://www.dit.ie/management/staff/maryregan/">Published by</a></li>
</ul>
</div>

<p align="center"><iframe width="560" height="315" src="https://www.youtube.com/embed/RRPU_mfhYGA?autoplay=1" frameborder="0" allowfullscreen></iframe></p>


</body>

app/views/pages/home.html.erb
The current time and date is : <%=@variable1%>
<html>
<head>

	<div id="footer">
		<p align="center">Zaid Kurchied</p>
		<h1 align="center"><font size="12" color="Grey">WHEEL AND DEAL</font></h1>
	</div>
	</body>

<style> 


body {
    background-image: url("../assets/rails.jpg"), url("img_flwr.gif");
    background-color: #cccccc;
}
</style>
</head>
<head> 
	<style type="text/css"> .pic{ width:1400px; height:1117px; 
	background: url("../assets/red.jpg") no-repeat; } 
	.text
{ 
	width:340px; height:217px; background:#FFF; opacity:0; 
} 	.pic:hover .text 
{ 
	opacity:0.6; text-align:justify; color:#000000; font-size:20px; font-weight:700; 
	font-family:"Times New Roman", Times, serif; padding:30px; } 
	</style>
</head> 
 <body> 
 <div class="pic"> 
 <div class="text"> Dream it.Drive it.Live it.Every luxury must be paid for, and everything is a luxury, starting here.</div>
<script>





app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
     <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
     </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password%>
  </div
  
  <div class="field">
   <%= f.label :password_confirmation%><br/>
   <%=f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Dob</th>
    <th>Photo</th>
    <th>Password digest</th>
    <th>Ad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.dob,id: :datepicker%></td>
    <td><%= user.photo %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.ad_id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Register Here</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Dob:</b>
  <%= @user.dob %>
</p>

<p>
  <b>Photo:</b>
<%= image_tag(@user.photo)  %>
</p>


<p>
  <b>Password :</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>